- name: modify nginx config
  template:
    src: nginx/pandora_console.conf
    dest: /etc/nginx/conf.d/pandora_console.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: modify pandora_console directory
  file:
    path: /var/www/pandora_console
    state: directory
    owner: nginx
    group: nginx
    recurse: yes
