- name: modify php5-fpm config
  template:
    src: php5-fpm/pandora_console.conf
    dest: /etc/php5/fpm/pool.d/pandora_console.conf
    owner: root
    group: root
    mode: 0644
  notify: restart php5-fpm
